usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
allowWorldTeleport: true
defaultWEAnywhere: true
NbClearSpools: 3
NbBlocksPerClearStep: 50000
AdvancedLogging: false
PlotEnterAnnouncement: false
mySQLConverter: true
Version: 0.17
ExpirePlotCleanupTimer: 90

